<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PinkSlipsTool</AssemblyName>
    <RootNamespace>PinkSlipsTool</RootNamespace>
    <ApplicationIcon>PinkSlipsTool.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Images\PinkSlipsHeader.png" />
    <Resource Include="Images\C4Logo.png" />
  </ItemGroup>
</Project>
